apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ia-case-migration App
name: ia-case-migration
home: https://github.com/hmcts/ia-case-migration
version: 0.0.1
maintainers:
  - name: HMCTS iac team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 4.0.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
